### ISSUE TITLE
登陆提示未知的错误

### ISSUE THREAD

**Issue by hugoren** [amas-eye/amas#2]
按照readme的docker脚本说明安装，登陆时候，提示未知的错误

**Comment by EaconTang** [comment]
你好，能否提供一些错误的信息/截图？

**Comment by feeir** [comment]
@EaconTang 
![_20180530145746](https://user-images.githubusercontent.com/18325267/40704223-1a3e9a36-641a-11e8-88fa-924cee47a7d8.png)

**Comment by feeir** [comment]
![Uploading 微信截图_20180530145647.png…]()

**Comment by EaconTang** [comment]
Duplicate of what's in 
https://github.com/amas-eye/amas/issues/4
