### ISSUE TITLE
Expect the source code to open again.

### ISSUE THREAD

**Issue by wangxu0** [amas-eye/amas#3]
When I wanted to contribute code, I found that the source code was deleted, but it can also be seen in the commit log. Expect the source code to open again.

**Comment by EaconTang** [comment]
The source code is available, check these repos:
- [argus-web](https://github.com/amas-eye/argus-web)
- [argus-statistics](https://github.com/amas-eye/argus_statistics)
- [argus-alert](https://github.com/amas-eye/argus_alert)
- [argus-collector](https://github.com/amas-eye/argus_collector)

Other repos would be released in few months:
- [argus-chain](https://github.com/amas-eye/argus_chain)
- [argus-aiops](https://github.com/amas-eye/argus_aiops)

For now, more documents and code comments are still in process, your attention and suggestion are welcome.
