### ISSUE TITLE
登录提示 未知的错误

### ISSUE THREAD

**Issue by jevic** [amas-eye/amas#4]
使用默认密码: admin / 123 登录提示未知的错误 什么情况？
[WARN] Redis server does not require a password, but a password was supplied
执行初始化报这个错误

**Comment by zhaomgyu** [comment]
同样的错误，求指导

**Comment by EaconTang** [comment]
@ray1888 @haooodev 帮忙看一下

**Comment by ray1888** [comment]
@jevic  方便发个截图吗？

**Comment by feeir** [comment]
![_20180530145746](https://user-images.githubusercontent.com/18325267/40704177-fe9c5502-6419-11e8-8624-5fefcf31e86e.png)
@ray1888

**Comment by luoxiaoming082** [comment]
@ray1888 @EaconTang 是否跟数据库关联出了问题,我部署了三次,都会报相同的错误!
![image](https://user-images.githubusercontent.com/39754212/40759320-2351f80c-64c4-11e8-85d2-63480ca194ea.png)

**Comment by lcstar** [comment]
在服务器上部署 远程登录显示未知错误 打开浏览器的控制台看HTTP请求 好像是请求到本地的8080端口 而并不是请求到服务器的8080端口
![wx20180601-080934](https://user-images.githubusercontent.com/15100432/40814531-57b05fda-6573-11e8-9bbd-db288d08d7f5.png)

**Comment by feeir** [comment]
[root@iZ2ze5gg8kaewzjs0b00sbZ pengfei.tian]# docker ps -a |grep web
0b73ff3bf054        eacon/argus-web          "run"                    44 hours ago        Up 44 hours         0.0.0.0:8080->8080/tcp                                              web
[root@iZ2ze5gg8kaewzjs0b00sbZ pengfei.tian]# docker exec -it 0b73ff3bf054 /bin/bash
root@0b73ff3bf054:/opt/amas#
your_server_ip=''
find ./ -type f|xargs grep --color '127.0.0.1'|awk -F ':' '{print $1}' |xargs sed -i 's/127.0.0.1/${your_server_ip}/'
然后可以登录了

**Comment by EaconTang** [comment]
@feeir 是这个问题。我们内部版本已经有动态获取ip，开源版本还没有。
我们会把最新版本的代码merge到github版本，测试ok后更新发布出来。
